#!/usr/bin/env zsh

# Set XDG Base Directory Specification environment variables
test "$XDG_BIN_HOME"    || export XDG_BIN_HOME="$HOME/.local/bin"
test "$XDG_CACHE_HOME"  || export XDG_CACHE_HOME="$HOME/.cache"
test "$XDG_CONFIG_HOME" || export XDG_CONFIG_HOME="$HOME/.config"
test "$XDG_DATA_HOME"   || export XDG_DATA_HOME="$HOME/.local/share"
test "$XDG_LIB_HOME"    || export XDG_LIB_HOME="$HOME/.local/lib"

# Set $PATH environment variable
export PATH=$XDG_BIN_HOME:$PATH

# Set ZSH comdump file
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/zcompdump-${HOST}-${ZSH_VERSION}"

# ZSH dotfiles in .config/zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# set location for zinit paths
# This zsh configuration uses zinit as its plugin manage
# https://github.com/zdharma/zinit
declare -A ZINIT
export ZINIT[BIN_DIR]="$ZDOTDIR/zinit/bin"
export ZINIT[HOME_DIR]="$ZDOTDIR/zinit"
export ZINIT[PLUGINS_DIR]="$ZDOTDIR/zinit/plugins"
export ZINIT[COMPLETIONS_DIR]="$ZDOTDIR/zinit/completions"
export ZINIT[SNIPPETS_DIR]="$ZDOTDIR/zinit/snippets"
export ZINIT[ZCOMPDUMP_PATH]="$ZDOTDIR/zinit/.zcompdump"

# set location for tmux plugin manager
export TMUX_PLUGIN_MANAGER_PATH=$XDG_CONFIG_HOME/tmux/plugins/

# Set language environment
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Set preferred vim locations
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi


# Compilation flags
export ARCHFLAGS="-arch x86_64"


# Bundler config vars
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundler/cache"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundler/config"
export BUNDLE_USER_PLUGIN="$XDG_CACHE_HOME/bundler/plugin"

# Node / NPM config vars
export NODE_REPL_HISTORY="$XDG_CACHE_HOME/node/node_repl_history"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"

# Docker config folder location
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

# Stop Homebrew logging
export HOMEBREW_NO_ANALYTICS=1

# ASDF configuration
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME="$XDG_CONFIG_HOME/asdf/tool-versions"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
