# First things first, add locality script
export PATH="$HOME/dotfiles/bin:$HOME/.local/bin:$PATH"

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f" || \
        print -P "%F{160}▓▒░ The clone has failed.%f"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit installer's chunk
setopt promptsubst

# Oh my zsh plugins
# git cloudapp node npm wd brew osx extract z zsh-syntax-highlighting zsh-autosuggestions dirnav
#
zinit ice wait lucid
zinit snippet OMZ::lib/git.zsh

# some OMZ themes use this plugin

zinit ice wait atload"unalias grv" lucid
zinit snippet OMZ::plugins/git/git.plugin.zsh
zinit snippet OMZ::plugins/zsh_reload/zsh_reload.plugin.zsh

zinit ice wait lucid
zinit snippet OMZ::plugins/brew/brew.plugin.zsh

zinit ice svn wait lucid
zinit snippet OMZ::plugins/golang

zinit ice svn; zinit snippet OMZ::plugins/wd

zinit ice wait=1 lucid
zinit snippet OMZ::plugins/node/node.plugin.zsh

zinit ice wait=1 lucid
zinit snippet OMZ::plugins/npm/npm.plugin.zsh

zinit ice svn wait lucid
zinit snippet OMZ::plugins/osx

zinit ice as"completion"
zinit snippet OMZ::plugins/pip/_pip

zinit ice wait lucid
zinit snippet OMZ::plugins/pip/pip.plugin.zsh

zinit ice wait lucid
zinit snippet OMZ::plugins/pipenv/pipenv.plugin.zsh


zinit ice wait lucid
zinit snippet OMZ::plugins/vscode/vscode.plugin.zsh

zinit ice as"completion"
zinit snippet OMZ::plugins/pylint/_pylint

zinit ice wait lucid
zinit snippet OMZ::plugins/pylint/pylint.plugin.zsh

zinit ice wait lucid
zinit snippet OMZ::plugins/python/python.plugin.zsh


zinit ice wait=1 lucid
zinit light lukechilds/zsh-better-npm-completion

zinit ice wait lucid
zinit load BugliL/zsh-dirnav

PS1="READY >" # provide a nice prompt till the theme loads
zinit ice wait'!' lucid
zinit snippet $HOME/dotfiles/zsh/zsh/cobalt2-iterm.zsh-theme

zinit snippet OMZ::plugins/docker-compose/docker-compose.plugin.zsh
 if [[ -d '/Applications/Docker.app' ]]; then
   zinit ice as'completion' wait'' multisrc'{docker,docker-compose}.zsh-completion'
   zinit light '/Applications/Docker.app/Contents/Resources/etc'
 fi

zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS

# fzf
zinit ice from"gh-r" as"program"
zinit load junegunn/fzf-bin
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# init direnv
zinit ice from"gh-r" as"program" mv"direnv* -> direnv" atclone'./direnv hook zsh > zhook.zsh' atpull'%atclone' pick"direnv"
zinit light direnv/direnv

zinit ice "rupa/z" pick"z.sh"; zinit light "rupa/z"
zinit load changyuheng/fz

zinit ice wait"0" lucid blockf
zinit ice wait blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions

zinit ice wait atinit"zpcompinit; zpcdreplay"
zinit light zdharma/fast-syntax-highlighting

zinit ice wait atload"_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions

source  $HOME/dotfiles/zsh/zsh/includes.zsh

zinit ice wait"0" lucid atinit"zpcompinit; zpcdreplay"

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
# pyenv
    if [[ -n "$PYENV_ROOT" && -d "$PYENV_ROOT" ]]; then
        if [[ ! -f "${PYENV_ROOT}/zpyenv.zsh" ]]; then
            {
                pyenv init - --no-rehash zsh
                pyenv virtualenv-init - zsh
            } >"${PYENV_ROOT}/zpyenv.zsh"
        fi

        zinit snippet "${PYENV_ROOT}/zpyenv.zsh"
    fi

 # Fix for git submodule issues and gettext.sh
# https://github.com/pyenv/pyenv/issues/688
#
export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1

#eval "$(/Users/cvardema/anaconda3/bin/conda shell.YOUR_SHELL_NAME hook)"

# source /Users/cvardema/anaconda3/bin/activate  # commented out by conda initialize

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/cvardema/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/cvardema/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/cvardema/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/cvardema/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export CONDA_AUTO_ACTIVATE_BAS=false
