# Status line
  set-option -g status on
  set-option -g status-style fg=cyan,bg=brightblack
  set-option -g status-justify centre
  set-option -g status-left-length 40
  set-option -g status-right-length 45
#  set-option -g status-right '#($XDG_CONFIG_HOME/tmux/tmux-battery-indicator.sh) #(date "+%a %b %d %I:%M%p")'
  set -g status-right '#[bg=white]#{battery_status_bg} Batt: #{battery_icon} #{battery_percentage} #{battery_remain} | %a %h-%d %H:%M '
  set-option -g window-status-format ' #I) #W '
  set-option -g window-status-current-format ' #I) #W '
  set-option -g window-status-separator ''
  set-option -g window-status-current-style 'reverse'
  set-option -g window-status-activity-style 'blink'
  set-option -g window-status-bell-style 'blink'


